export const CYCLES_MINTING_CID = 'rkp4c-7iaaa-aaaaa-aaaca-cai'
export const LEDGER_CID = process.env.NODE_ENV !== 'development' ? 'ryjl3-tyaaa-aaaaa-aaaba-cai' : 'ryjl3-tyaaa-aaaaa-aaaba-cai'
export const FACTORY_ID = process.env.NODE_ENV !== 'development' ? 'hfz6w-oyaaa-aaaah-qaciq-cai' : 'qaa6y-5yaaa-aaaaa-aaafa-cai'
export const REGISTRY_ID = process.env.NODE_ENV !== 'development' ? 'hm6ah-miaaa-aaaah-aadeq-cai' : 'qsgjb-riaaa-aaaaa-aaaga-cai'
export const CSPT_CID = process.env.NODE_ENV !== 'development' ? 'c3gue-yyaaa-aaaah-aapwq-cai' : 'tzq7c-xqaaa-aaaaa-aaamq-cai'
export const NNS_UI_CID = process.env.NODE_ENV !== 'development' ? 'qoctq-giaaa-aaaaa-aaaea-cai' : 'qoctq-giaaa-aaaaa-aaaea-cai'
export const EXCHANGE_0_CID = process.env.NODE_ENV !== 'development' ? 'i3n4m-ciaaa-aaaaa-aac4a-cai' : 'i3n4m-ciaaa-aaaaa-aac4a-cai'
export const II_URL = process.env.NODE_ENV !== 'development' ? 'https://identity.ic0.app/#authorize' : 'http://localhost:8080/'
export const HOST_URL = process.env.NODE_ENV !== 'development' ? 'https://mainnet.dfinity.network' : 'http://localhost:8000/'
export const IC_CANISTER_ID = 'hl7gt-bqaaa-aaaah-aadea-cai'
